# Generated by Django 4.0.1 on 2022-03-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoc', '0002_post_preference_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
