# Generated by Django 4.0.1 on 2022-03-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mainpreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mainpreference',
            name='post',
        ),
        migrations.RemoveField(
            model_name='mainpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='mainPost',
        ),
        migrations.DeleteModel(
            name='mainPreference',
        ),
    ]
